# Generated by Django 5.2.3 on 2025-06-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Reclutamiento', 'Reclutamiento'), ('Contratacion', 'Contratacion')], default='Reclutamiento', max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rh', models.CharField(blank=True, max_length=3, null=True)),
                ('ciudad_expedicion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_domicilio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('cliente', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Oferta Laboral',
                'verbose_name_plural': 'Ofertas Laborales',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.candidato')),
                ('oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.ofertalaboral')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('examenes', models.FileField(blank=True, null=True, upload_to='examenes/')),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contratacion.postulacion')),
            ],
            options={
                'verbose_name': 'Orden de Contratación',
                'verbose_name_plural': 'Órdenes de Contratación',
            },
        ),
    ]
