# Generated by Django 5.2.3 on 2025-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.CharField(choices=[('Reclutamiento', 'Reclutamiento'), ('Contratacion', 'Contratacion')], default='Reclutamiento', max_length=20, null=True),
        ),
    ]
